### ISSUE TITLE
Store search term in url

### ISSUE THREAD

**Issue by pigpiggo-net** [pigpiggo-net/pigpiggo#2]
At the moment search terms are not added to the url so if you refresh the page the search term will be cleared. Also you can't send someone a link to pigpiggo.net containing a search term and have it work.

**Comment by pachecohjr** [comment]
I noticed that when entering a keyword, there is no new URL that I could copy & paste a link for viewers to click in regards to a specific keyword made. Like, how Google shows the long URL and any certain parameters such as filtering or options, are allowed as well. i.e.: https://www.google.com/search?q=pigpiggo+vs+duckduckgo

Why do you think it is continuously displaying only the domain page and not displaying the query on the address field?

**Comment by pigpiggo-net** [comment]
Yeah I just didn't add that feature yet, added it now though, should be live on the site shortly
