### ISSUE TITLE
Add date filter/selector or equivalent feature

### ISSUE THREAD

**Issue by pigpiggo-net** [pigpiggo-net/pigpiggo#3]
Add a date filter to the search page that allows you to search for captions between certain dates.   
This could for example two calendars (from and to) but we can discuss other ideas too.  

Lofty idea: Create a timeline (probably using an existing plugin) with markers/ranges for the "different eras of dsp" e.g. panda, kat, the incident, machinima, curse, the move across the country, the wedding etc. etc. Maybe have it so you can drag a section of the timeline and only display results from videos in that period.  

Even loftier idea: Show all results sorted by date by default with paging as with Google etc. Also display the timeline mentioned in lofty idea number 1, with a graph showing number of mentions or number of videos containing the search term. Clicking or selection a period in the timeline then shows results for that period.

**Comment by pachecohjr** [comment]
Wow, I have never seen this implemented on Google. Is there a way you can show this ? This can get pretty lofty

**Comment by pigpiggo-net** [comment]
Google doesn't have exactly this, was just using them as an example of the paging feature as a common search engine practice for handling large numbers of results.

**Comment by pachecohjr** [comment]
This seems like the most interesting yet more challenging feature to add. This would make for a nice end result. I'm in when I get time. I need to take a good look at this source when time warrants.

**Comment by pigpiggo-net** [comment]
Let's just make this a simple date filter for now, could use a plugin such as react-datepicker
and add From date and To date fields, both optional

**Comment by DarkChironYT** [comment]
Sorry I meant to mention earlier but I am making progress on this. I'm not that familiar with the React library so I'm learning as I go on it. I have the fields added and required functionality for taking inputs, but React doesn't like traditional "<input type='date'/>" fields. I'll give the react-datepicker a look over.
I'll have plenty of time to work on it this week. Hopefully I'll have something for your examination in the next few days.

**Comment by pigpiggo-net** [comment]
Ok I'm guessing @pachecohjr hasn't had a chance to look at it yet so let's let @DarkChironYT take it and @pachecohjr can take another one. Let me/us know here or in the discord if you need help with anything.

**Comment by DarkChironYT** [comment]
> Ok I'm guessing @pachecohjr hasn't had a chance to look at it yet so let's let @DarkChironYT take it and @pachecohjr can take another one. Let me/us know here or in the discord if you need help with anything.

What discord are we having discussions on? @pigpiggo-net

**Comment by beskhu3epnm** [comment]
> What discord are we having discussions on? @pigpiggo-net
https://discord.gg/6hJaBnh

**Comment by pigpiggo-net** [comment]
@DarkChironYT put in the pull request and it's up on the site now so closing this. Create a new issue for any additions/fixes etc
