### ISSUE TITLE
Only displaying the first 200 results

### ISSUE THREAD

**Issue by pachecohjr** [pigpiggo-net/pigpiggo#4]
I noticed that only the first 200 results are displayed and there is no way to continue to the next 200 results. How would this be able to implemented? How are the first 200 results displayed in the first case? Via SQL query?

**Comment by pigpiggo-net** [comment]
Yeah it's an intentional limit in code to keep things from getting too slow while a proper solution (probably pagination) gets made.

**Comment by pigpiggo-net** [comment]
Added pagination, all results can be accessed so closing this
